# general
gpu_id: 0
use_gpu: True
seed: 0
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved/movielens-20m'
show_progress: True
save_dataset: True
save_dataloaders: True

# Dataset Parameters
## Atomic File Format
field_separator: "\t"
seq_separator: " "
## Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
seq_len: ~
## Label for Point-wise DataLoader
LABEL_FIELD: label
threshold: ~
## NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_
## Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
## Knowledge-based Model Needed
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id
## Selectively Loading
load_col:
    inter: [user_id, item_id, timestamp, rating]
    # user: [user_id, age, gender, occupation, zip_code]
    # item: [item_id, movie_title, release_year, genre]
# unload_col:
    # inter: [timestamp, rating]
# unused_col:
#     inter: [timestamp, rating]
additional_feat_suffix: ~
## Filtering
rm_dup_inter: ~
val_interval:
    rating: "[4,inf)"
    # timestamp: "[97830000, inf)"
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[0,inf)"
## Preprocessing
alias_of_user_id: ~
alias_of_item_id: ~
alias_of_entity_id: ~
alias_of_relation_id: ~
preload_weight: ~
normalize_field: ~
normalize_all: ~

kg_reverse_r: False
entity_kg_num_interval: "[0,inf)"
relation_kg_num_interval: "[0,inf)"
benchmark_filename: ~

# Training and evaluation config
epochs: 200
stopping_step: 20
train_batch_size: 1024
neg_sampling:
    uniform: 1
learner: adam
learning_rate: 0.001
eval_step: 1
# clip_grad_norm: None
weight_decay: 0.0
loss_decimal_place: 4

# Evaluation Congig
eval_batch_size: 1024
eval_args:
    group_by: 'user'
    order: 'TO' 
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
repeatable: False
metrics: ['Recall', 'ItemCoverage', 'NDCG', 'Hit']
topk: [20]
valid_metric: Recall@20
valid_metric_bigger: True
metric_decimal_place: 4

# Model Hyperparameters
latent_dimension : 200
mlp_hidden_size: 600
dropout_prob: 0.5
anneal_cap: 0.2
total_anneal_steps: 200000 

# https://qiita.com/fufufukakaka/items/77878c1e23338345d4fa


# Other Hyper Parameters: 
# worker: 0
# wandb_project: recbole
# shuffle: True
# require_pow: False
# enable_amp: False
# enable_scaler: False
# transform: None
# # embedding_size: 64
# numerical_features: []
# discretization: None
# # MODEL_TYPE: ModelType.GENERAL
# # MODEL_INPUT_TYPE: InputType.PAIRWISE
# # eval_type: EvaluatorType.RANKING
single_spec: True
# nproc: 1
# offset: 0
# local_rank: 0
# device: cuda
# world_size: 1
# ip: "192.172.255.000"
# port: 22
# valid_neg_sample_args:
#     distribution: 'uniform'
#     sample_num: 'none'
# test_neg_sample_args:
#     distribution: 'uniform'
#     sample_num: 'none'